 repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: ^scripts/.*\.js$
        additional_dependencies:
          - prettier@3.1.0