# Site Configuration
site:
  title: Your Site Name
  description: Your site description
  url: https://yoursite.com
  language: en

# Default Author Configuration
authors:
  default:
    name: Author Name
    bio: Short author bio
    avatar: /path/to/avatar.jpg
  # Add more authors as needed
  # john:
  #   name: John Doe
  #   bio: John's bio
  #   avatar: /path/to/john.jpg

# Navigation
nav:
  - title: Home
    url: /
  - title: Blog
    url: /blog
  - title: About
    url: /about

# Social Media
social:
  twitter: yourtwitterhandle
  github: yourgithubhandle
  linkedin: yourlinkedinhandle
